  - name: install neutron (Ubuntu)
    apt:
      name:
        - neutron-server
        - neutron-plugin-ml2
        - neutron-linuxbridge-agent
        - neutron-dhcp-agent
        - neutron-metadata-agent
      state: present

  - name: remove other connection in database
    lineinfile:
      path: /etc/neutron/neutron.conf
      regexp: '^connection = '
      state: absent
      insertafter: '^\[database\]'

  - name: add connection in database
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'connection = mysql+pymysql://neutron:jenmar0112@clone1/neutron'
      state: present
      insertafter: '^\[database\]'

  - name: add core_plugin in DEFAULT
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'core_plugin = ml2'
      state: present
      insertafter: '^\[DEFAULT\]'

  - name: add service_plugins in DEFAULT
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'service_plugins ='
      state: present
      insertafter: '^\[DEFAULT\]'

  - name: add transport_url in DEFAULT
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'transport_url = rabbit://openstack:jenmar0112@clone1'
      state: present
      insertafter: '^\[DEFAULT\]'

  - name: add auth_strategy in DEFAULT
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'auth_strategy = keystone'
      state: present
      insertafter: '^\[DEFAULT\]'

  - name: add authenticate in keystone_authtoken
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'www_authenticate_uri = http://controller:5000'
      state: present
      insertafter: '^\[keystone_authtoken\]'

  - name: add auth_url in keystone_authtoken
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'auth_url = http://controller:5000'
      state: present
      insertafter: '^\[keystone_authtoken\]'

  - name: add memcached_servers in keystone_authtoken
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'memcached_servers = controller:11211'
      state: present
      insertafter: '^\[keystone_authtoken\]'

  - name: add auth_type in keystone_authtoken
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'auth_type = password'
      state: present
      insertafter: '^\[keystone_authtoken\]'

  - name: add project_domain_name in keystone_authtoken
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'project_domain_name = Default'
      state: present
      insertafter: '^\[keystone_authtoken\]'

  - name: add user_domain_name in keystone_authtoken
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'user_domain_name = Default'
      state: present
      insertafter: '^\[keystone_authtoken\]'

  - name: add project_name in keystone_authtoken
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'project_name = service'
      state: present
      insertafter: '^\[keystone_authtoken\]'

  - name: add username in keystone_authtoken
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'username = neutron'
      state: present
      insertafter: '^\[keystone_authtoken\]'

  - name: add password in keystone_authtoken
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'password = jenmar0112'
      state: present
      insertafter: '^\[keystone_authtoken\]'

  - name: add notify_nova_on_port_status_changes in DEFAULT
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'notify_nova_on_port_status_changes = true'
      state: present
      insertafter: '^\[DEFAULT\]'

  - name: add notify_nova_on_port_data_changes in DEFAULT
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'notify_nova_on_port_data_changes = true'
      state: present
      insertafter: '^\[DEFAULT\]'

  - name: add auth_url in nova
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'auth_url = http://controller:5000'
      state: present
      insertafter: '^\[nova\]'

  - name: add auth_type in nova
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'auth_type = password'
      state: present
      insertafter: '^\[nova\]'

  - name: add project_domain_name in nova
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'project_domain_name = default'
      state: present
      insertafter: '^\[nova\]'

  - name: add user_domain_name in nova
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'user_domain_name = default'
      state: present
      insertafter: '^\[nova\]'

  - name: add region_name in nova
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'region_name = RegionOne'
      state: present
      insertafter: '^\[nova\]'

  - name: add project_name in nova
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'project_name = service'
      state: present
      insertafter: '^\[nova\]'

  - name: add username in nova
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'username = nova'
      state: present
      insertafter: '^\[nova\]'

  - name: add password in nova
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'password = jenmar0112'
      state: present
      insertafter: '^\[nova\]'

  - name: add lock_path in oslo_concurrency
    lineinfile:
      path: /etc/neutron/neutron.conf
      line: 'lock_path = /var/lib/neutron/tmp'
      state: present
      insertafter: '^\[oslo_concurrency\]'

  - name: add type_drivers in ml2
    lineinfile:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      line: 'type_drivers = flat,vlan'
      state: present
      insertafter: '^\[ml2\]'

  - name: add tenant_network_types in ml2
    lineinfile:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      line: 'tenant_network_types ='
      state: present
      insertafter: '^\[ml2\]'

  - name: add mechanism_drivers in ml2
    lineinfile:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      line: 'mechanism_drivers = linuxbridge'
      state: present
      insertafter: '^\[ml2\]'

  - name: add extension_drivers in ml2
    lineinfile:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      line: 'extension_drivers = port_security'
      state: present
      insertafter: '^\[ml2\]'

  - name: add flat_networks in ml2_type_flat
    lineinfile:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      line: 'flat_networks = provider'
      state: present
      insertafter: '^\[ml2_type_flat\]'

  - name: add enable_ipset in securitygroup
    lineinfile:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      line: 'enable_ipset = true'
      state: present
      insertafter: '^\[securitygroup\]'

  - name: add physical_interface_mappingst in linux_bridge
    lineinfile:
      path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
      line: 'physical_interface_mappings = provider:PROVIDER_INTERFACE_NAME'
      state: present
      insertafter: '^\[linux_bridge\]'

  - name: add enable_vxlan in vxlan
    lineinfile:
      path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
      line: 'enable_vxlan = false'
      state: present
      insertafter: '^\[vxlan\]'

  - name: add enable_security_group in securitygroup
    lineinfile:
      path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
      line: 'enable_security_group = true'
      state: present
      insertafter: '^\[securitygroup\]'

  - name: add firewall_driver in securitygroup
    lineinfile:
      path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
      line: 'firewall_driver = neutron.agent.linux.iptables_firewall.IptablesFirewallDriver'
      state: present
      insertafter: '^\[securitygroup\]'

  - name: add interface_driver in DEFAULT
    lineinfile:
      path: /etc/neutron/dhcp_agent.ini
      line: 'interface_driver = linuxbridge'
      state: present
      insertafter: '^\[DEFAULT\]'

  - name: add dhcp_driver in DEFAULT
    lineinfile:
      path: /etc/neutron/dhcp_agent.ini
      line: 'dhcp_driver = neutron.agent.linux.dhcp.Dnsmasq'
      state: present
      insertafter: '^\[DEFAULT\]'

  - name: add enable_isolated_metadata in DEFAULT
    lineinfile:
      path: /etc/neutron/dhcp_agent.ini
      line: 'enable_isolated_metadata = true'
      state: present
      insertafter: '^\[DEFAULT\]'

  - name: add nova_metadata_host in DEFAULT
    lineinfile:
      path: /etc/neutron/metadata_agent.ini
      line: 'nova_metadata_host = controller'
      state: present
      insertafter: '^\[DEFAULT\]'

  - name: add metadata_proxy_shared_secret in DEFAULT
    lineinfile:
      path: /etc/neutron/metadata_agent.ini
      line: 'metadata_proxy_shared_secret = METADATA_SECRET'
      state: present
      insertafter: '^\[DEFAULT\]'

  - name: restart neutron-server service
    service:
      name: neutron-server
      state: restarted

  - name: restart neutron-linuxbridge-agent service
    service:
      name: neutron-linuxbridge-agent
      state: restarted

  - name: restart neutron-dhcp-agent service
    service:
      name: neutron-dhcp-agent
      state: restarted

  - name: neutron-metadata-agent service
    service:
      name: neutron-metadata-agent
      state: restarted
